spring:
    datasource:
        generate-unique-name: false
        name: tacocloud

# spring:
#     cassandra:
#         keyspace-name: taco_cloud
#         schema-action: recreate
#         local-datacenter: datacenter1
#         username: tacocloud
#         password: s3cr3tP455w0rd

# spring:
#     data:
#         mongodb:
#             host: mongodb.tacocloud.com
#             port: 27017
#             username: tacocloud
#             password: s3cr3tP455w0rd
#             database: tacoclouddb